/**
 * 召回评测金标集（中文技术面试域）。设计原则:**查询故意改写/同义,不与相关 chunk 共享表层词**——
 * 这样纯 BM25 会漏,逼出真语义召回;90% 才是有意义的硬指标(不是送分)。relevant = 该查询应召回的 chunk id。
 */
export interface GChunk { id: string; text: string }
export interface GQuery { q: string; relevant: string[] }

export const CORPUS: GChunk[] = [
  { id: 'limit-sliding', text: '滑动窗口限流把时间切成小格,统计最近一段时间的请求数,超过阈值即拒绝,比固定窗口更平滑无临界突刺。' },
  { id: 'limit-tokenbucket', text: '令牌桶以恒定速率往桶里放令牌,请求到来取一个令牌,桶空则限流;允许一定突发流量。' },
  { id: 'limit-leakybucket', text: '漏桶以固定速率漏水处理请求,入队超过容量则丢弃,输出速率恒定,削峰但不允许突发。' },
  { id: 'limit-rediscounter', text: 'Redis 用 INCR 对 key 计数并设过期时间实现分布式限流,Lua 脚本保证计数与判断的原子性。' },
  { id: 'lock-redis', text: 'Redis 分布式锁用 SET key val NX PX 加锁,value 写唯一标识,解锁用 Lua 比对后删除,避免误删他人锁。' },
  { id: 'lock-redlock', text: 'Redlock 向多数 Redis 节点申请锁,过半成功才算获得,应对单点主从切换丢锁,但有时钟与争议。' },
  { id: 'lock-zk', text: 'ZooKeeper 临时顺序节点实现分布式锁,最小序号获得锁,监听前驱节点,会话断开自动释放,无死锁。' },
  { id: 'lock-dbunique', text: '数据库唯一索引插入一条记录当锁,插入成功即持锁,删除即释放,简单但无自动过期、性能差。' },
  { id: 'redis-rdb', text: 'RDB 在某时刻把内存快照 fork 子进程写盘,体积小恢复快,但宕机会丢最后一次快照后的数据。' },
  { id: 'redis-aof', text: 'AOF 追加每条写命令到日志,可配每秒或每写刷盘,数据更安全但文件大、恢复慢,可重写压缩。' },
  { id: 'redis-expire', text: 'Redis 过期键采用惰性删除加定期抽样删除组合,内存不足时按 maxmemory 淘汰策略剔除。' },
  { id: 'cache-penetration', text: '查询根本不存在的数据反复打到数据库叫缓存穿透,可用布隆过滤器拦截或缓存空值短过期。' },
  { id: 'cache-breakdown', text: '某个热点 key 失效瞬间大量请求同时压向数据库叫缓存击穿,可用互斥重建或逻辑过期不真删。' },
  { id: 'cache-avalanche', text: '大量 key 同一时间集中失效导致数据库瞬时被打垮叫缓存雪崩,过期时间加随机抖动可分散。' },
  { id: 'mysql-index-leftmost', text: '联合索引遵循最左前缀,查询条件从最左列连续命中才走索引,跳列或仅用右列会失效。' },
  { id: 'mysql-covering', text: '覆盖索引指查询的列都在索引上,无需回表读主键聚簇数据,显著减少随机 IO。' },
  { id: 'mysql-clustered', text: 'InnoDB 主键是聚簇索引,叶子节点存整行数据,二级索引叶子存主键值,故二级查询需回表。' },
  { id: 'mysql-mvcc', text: 'MVCC 通过隐藏版本号与 undo log 形成的版本链加 ReadView 实现读不加锁的快照读。' },
  { id: 'mysql-isolation', text: '可重复读隔离级别下同一事务多次读结果一致,InnoDB 配合间隙锁在该级别基本消除幻读。' },
  { id: 'jvm-gc-cms', text: 'CMS 以最短停顿为目标并发标记清除老年代,但会产生内存碎片且并发失败退化为 Full GC。' },
  { id: 'jvm-gc-g1', text: 'G1 把堆划分为大小相等的 Region,按回收价值优先回收,可设定停顿时间目标,兼顾吞吐与延迟。' },
  { id: 'jvm-gcroots', text: '可达性分析从 GC Roots(栈引用、静态变量、常量、本地方法引用)出发,不可达对象才可回收。' },
  { id: 'jvm-classload', text: '类加载双亲委派:加载请求先交父加载器,父加载不了才自己加载,保证核心类不被篡改。' },
  { id: 'pool-params', text: '线程池核心参数:核心线程数、最大线程数、队列、拒绝策略;任务先占核心,满了入队,再满才扩容。' },
  { id: 'pool-reject', text: '线程池拒绝策略有抛异常、调用者执行、丢弃最老、直接丢弃,可据是否容忍丢任务选择。' },
  { id: 'tcp-handshake', text: 'TCP 三次握手:客户端 SYN、服务端 SYN+ACK、客户端 ACK,双方确认收发能力后建立连接。' },
  { id: 'tcp-wave', text: 'TCP 四次挥手分别关闭两个方向,主动方进入 TIME_WAIT 等待 2MSL 确保末次 ACK 到达。' },
  { id: 'http-cache', text: '强缓存用 Cache-Control/Expires 不发请求直接用本地;协商缓存用 ETag/Last-Modified 回源校验 304。' },
  { id: 'mq-idempotent', text: '消息消费要幂等:用唯一业务 id 加去重表或状态机,保证重复投递只生效一次。' },
  { id: 'mq-order', text: '消息保序需同一业务键路由到同一分区/队列且单线程消费,否则并发消费打乱顺序。' },
  { id: 'mq-backlog', text: '消息积压可临时扩消费者并发与分区,或先快速落库再异步处理,排查下游瓶颈。' },
  { id: 'consistent-hash', text: '一致性哈希把节点和 key 映射到哈希环,扩缩容只影响相邻区间,虚拟节点解决数据倾斜。' },
  { id: 'cap-theorem', text: 'CAP 中分区容忍必须保证,只能在一致性与可用性间取舍;CP 牺牲可用,AP 牺牲强一致。' },
  { id: 'sharding', text: '分库分表按用户 id 或时间水平拆分,需处理跨片查询、分布式 id、扩容数据迁移。' },
  { id: 'idempotent-token', text: '接口幂等可用前置令牌:下单前领 token,提交时校验并删除 token,重复提交因 token 已消失被拒。' },
  { id: 'es-inverted', text: '倒排索引记录每个词到包含它的文档列表,搜索时取词的文档集合求交并按相关性打分。' },
];

export const QUERIES: GQuery[] = [
  { q: '接口被恶意刷量怎么平滑地挡住突发流量', relevant: ['limit-sliding'] },
  { q: '想允许偶尔的流量尖峰又能整体控速用什么算法', relevant: ['limit-tokenbucket'] },
  { q: '让请求严格匀速流出不允许爆发', relevant: ['limit-leakybucket'] },
  { q: '多台机器共享一个调用次数上限如何实现', relevant: ['limit-rediscounter'] },
  { q: '多个服务抢同一资源怎么用缓存中间件互斥', relevant: ['lock-redis'] },
  { q: '主从切换时锁失效有没有更可靠的多节点方案', relevant: ['lock-redlock'] },
  { q: '用协调服务做互斥且客户端崩了能自动放锁', relevant: ['lock-zk'] },
  { q: '不想引入额外组件只靠关系库怎么做互斥', relevant: ['lock-dbunique'] },
  { q: '内存数据库怎么做快照式持久化恢复最快', relevant: ['redis-rdb'] },
  { q: '怎样让缓存宕机后丢失的数据尽可能少', relevant: ['redis-aof'] },
  { q: '查一个库里压根没有的主键被反复打穿到后端怎么防', relevant: ['cache-penetration'] },
  { q: '一个超热的键刚好过期导致后端被瞬间压垮', relevant: ['cache-breakdown'] },
  { q: '一大批键同一刻集体失效把数据库冲垮', relevant: ['cache-avalanche'] },
  { q: '组合索引为什么有时候不生效跟列顺序的关系', relevant: ['mysql-index-leftmost'] },
  { q: '怎样查询能避免回表只读索引就够了', relevant: ['mysql-covering'] },
  { q: '二级索引查询为什么还要再查一次主键', relevant: ['mysql-clustered'] },
  { q: '事务里读数据不加锁还能看到一致快照靠什么机制', relevant: ['mysql-mvcc'] },
  { q: '怎么在不串行化的情况下基本消除幻读', relevant: ['mysql-isolation'] },
  { q: '追求低停顿的老年代并发回收器有什么缺点', relevant: ['jvm-gc-cms'] },
  { q: '能设定停顿目标又分区回收的现代垃圾收集器', relevant: ['jvm-gc-g1'] },
  { q: '判断一个对象能不能被回收从哪些根开始找引用', relevant: ['jvm-gcroots'] },
  { q: '为什么自定义的同名核心类加载不会覆盖系统类', relevant: ['jvm-classload'] },
  { q: '提交任务时线程怎么在核心数队列和最大数之间扩张', relevant: ['pool-params'] },
  { q: '任务太多放不下了线程池有哪些应对动作', relevant: ['pool-reject'] },
  { q: '建立连接为什么要来回确认三次', relevant: ['tcp-handshake'] },
  { q: '断开连接后主动方为什么要等一段时间才彻底关闭', relevant: ['tcp-wave'] },
  { q: '浏览器怎么决定直接用本地副本还是回服务器问一下', relevant: ['http-cache'] },
  { q: '同一条消息可能被投递多次怎么保证只处理一次', relevant: ['mq-idempotent'] },
  { q: '怎样保证消息按发送先后被处理不乱序', relevant: ['mq-order'] },
  { q: '下游消费不过来消息堆积了怎么快速泄洪', relevant: ['mq-backlog'] },
  { q: '加减节点时只迁移少量数据的哈希分布方式', relevant: ['consistent-hash'] },
  { q: '分布式系统网络分区下一致性和可用为何不能兼得', relevant: ['cap-theorem'] },
  { q: '单表数据量太大水平拆开后有哪些新麻烦', relevant: ['sharding'] },
  { q: '防止用户重复下单的前置票据方案', relevant: ['idempotent-token'] },
  { q: '全文搜索靠什么数据结构快速找到含某词的文档', relevant: ['es-inverted'] },
];
